name: JAVA Playwright E2E Tests - PR
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn clean install
      - name: Install Playwright
        run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
      - name: Check for tests to run
        run: mvn test-compile && echo "Compiled tests successfully"
      - name: Run tests
        run: mvn test
      - name: Store Playwright Traces and Videos From Failed Tests
        if: failure()
        uses: actions/upload-artifact@v4.3.1
        id: artifact-upload-step
        with:
          name: test-results
          path: test-results/
          retention-days: 7
      - name: Link Playwright Traces And Videos To Allure Report
        working-directory: allure-results
        if: failure()
        run: echo ARTIFACT_URL=${{ steps.artifact-upload-step.outputs.artifact-url }} >> environment.properties
      - name: Link Git Information And Browser Version To Allure Report
        working-directory: allure-results
        if: always()
        run: |
          echo GIT_BRANCH=${{ github.head_ref || github.ref_name }}  >> environment.properties
          echo GIT_COMMIT_ID=${{ github.sha }} >> environment.properties
          echo GIT_COMMIT_MESSAGE=$(git show -s --format=%s HEAD) >> environment.properties
          echo GIT_COMMIT_AUTHOR_NAME=$(git show -s --format='%ae' HEAD) >> environment.properties
          echo GIT_COMMIT_TIME=$(git show -s --format=%ci HEAD) >> environment.properties
          echo CHROME_VERSION=$(google-chrome --product-version) >> environment.properties
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history
      - name: Deploy Report To Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.MY_GITHUB_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history